/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'dd-bg': '#FFFFFF',
        'dd-surface': '#F7F7F7',
        'dd-surface-hover': '#EFEFEF',
        'dd-dark': '#2D2D2D',
        'dd-dark-row': '#3A3A3A',
        'dd-dark-hover': '#444444',
        'dd-accent': '#FF3008',
        'dd-accent-hover': '#E62B00',
        'dd-accent-light': '#FFF0EE',
        'dd-cyan': '#00B0FF',
        'dd-cyan-dark': '#0091EA',
        'dd-text': '#191919',
        'dd-text-secondary': '#767676',
        'dd-text-muted': '#ABABAB',
        'dd-border': '#E0E0E0',
        'dd-border-light': '#EEEEEE',
        'dd-green': '#00C853',
        'dd-red': '#E53935',
        'dd-amber': '#FFB300',
        // shadcn compatibility (keep these exact)
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'hero': ['2.5rem', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'h1': ['1.875rem', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'h2': ['1.5rem', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'h3': ['1.25rem', { lineHeight: '1.4', fontWeight: '600' }],
        'h4': ['1.125rem', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['1rem', { lineHeight: '1.5', fontWeight: '400' }],
        'body': ['0.875rem', { lineHeight: '1.5', fontWeight: '400' }],
        'sm': ['0.8125rem', { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '500' }],
        'xs': ['0.75rem', { lineHeight: '1.4', letterSpacing: '0.02em', fontWeight: '500' }],
        'mono-lg': ['1.25rem', { lineHeight: '1.2', letterSpacing: '0.02em', fontWeight: '500' }],
        'mono': ['0.9375rem', { lineHeight: '1.3', letterSpacing: '0.01em', fontWeight: '500' }],
        'mono-sm': ['0.8125rem', { lineHeight: '1.3', letterSpacing: '0.02em', fontWeight: '400' }],
      },
      borderRadius: {
        'sm': '6px',
        'md': '8px',
        'lg': '12px',
        'xl': '16px',
        'full': '9999px',
        'pin': '12px',
      },
      spacing: {
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '8': '32px',
        '10': '40px',
        '12': '48px',
        'header': '48px',
        'navbar': '96px',
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        'sm': '0 1px 2px rgba(0,0,0,0.05)',
        'md': '0 4px 6px rgba(0,0,0,0.07)',
        'lg': '0 10px 15px rgba(0,0,0,0.08)',
        'xl': '0 20px 25px rgba(0,0,0,0.1)',
        'panel': '0 1px 3px rgba(0,0,0,0.08)',
        'card': '0 4px 12px rgba(0,0,0,0.08)',
        'modal': '0 25px 50px -12px rgba(0,0,0,0.15)',
        'accent': '0 4px 16px rgba(59,130,246,0.2)',
        'winner': '0 4px 16px rgba(34,197,94,0.2)',
        'danger': '0 4px 16px rgba(239,68,68,0.2)',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "shake": {
          "0%, 100%": { transform: "translateX(0)" },
          "10%, 30%, 50%, 70%, 90%": { transform: "translateX(-4px)" },
          "20%, 40%, 60%, 80%": { transform: "translateX(4px)" },
        },
        "pin-shake": {
          "0%": { transform: "translateX(0)" },
          "20%": { transform: "translateX(-8px)" },
          "40%": { transform: "translateX(8px)" },
          "60%": { transform: "translateX(-4px)" },
          "80%": { transform: "translateX(4px)" },
          "100%": { transform: "translateX(0)" },
        },
        "pulse-glow": {
          "0%, 100%": { boxShadow: "0 0 0 0 rgba(59,130,246,0.4)" },
          "50%": { boxShadow: "0 0 20px 4px rgba(59,130,246,0.2)" },
        },
        "float-up": {
          "0%": { transform: "translateY(100vh)", opacity: "0" },
          "10%": { opacity: "0.6" },
          "90%": { opacity: "0.6" },
          "100%": { transform: "translateY(-10vh)", opacity: "0" },
        },
        "bg-zoom": {
          "0%": { transform: "scale(1)" },
          "100%": { transform: "scale(1.02)" },
        },
        "shimmer": {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "spin-once": {
          "0%": { transform: "rotate(0deg)" },
          "100%": { transform: "rotate(360deg)" },
        },
        "count-pulse": {
          "0%, 100%": { transform: "scale(1)" },
          "50%": { transform: "scale(1.2)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "shake": "shake 0.4s ease-in-out",
        "pin-shake": "pin-shake 0.4s ease-in-out",
        "pulse-glow": "pulse-glow 2s ease-in-out infinite",
        "float-up": "float-up 20s ease-in-out infinite",
        "bg-zoom": "bg-zoom 20s ease-in-out infinite alternate",
        "shimmer": "shimmer 1.5s linear infinite",
        "spin-once": "spin-once 0.5s ease-in-out",
        "count-pulse": "count-pulse 0.2s ease-in-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
